// Writes src/version.js from package.json's "version" field so the two never drift
// apart. package.json stays the single source of truth for the engine's version
// number; run this (directly, or via `npm run build`, which calls it first) whenever
// package.json's version changes.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

export function syncVersion() {
  const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
  const target = path.join(root, "src/version.js");
  const content = `// Generated by scripts/sync-version.js from package.json's "version" field.\n` +
    `// Do not edit by hand -- re-run \`node scripts/sync-version.js\` (or \`npm run build\`) after\n` +
    `// bumping package.json's version instead.\nexport const ENGINE_VERSION = ${JSON.stringify(pkg.version)};\n`;
  writeFileSync(target, content);
  return pkg.version;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const version = syncVersion();
  console.log(`src/version.js synced to ${version}`);
}
