// Generated by scripts/sync-version.js from package.json's "version" field.
// Do not edit by hand -- re-run `node scripts/sync-version.js` (or `npm run build`) after
// bumping package.json's version instead.
export const ENGINE_VERSION = "0.4.3";
